require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TodolistsController do

  # This should return the minimal set of attributes required to create a valid
  # Todolist. As you add validations to Todolist, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all todolists as @todolists" do
      todolist = Todolist.create! valid_attributes
      get :index
      assigns(:todolists).should eq([todolist])
    end
  end

  describe "GET show" do
    it "assigns the requested todolist as @todolist" do
      todolist = Todolist.create! valid_attributes
      get :show, :id => todolist.id.to_s
      assigns(:todolist).should eq(todolist)
    end
  end

  describe "GET new" do
    it "assigns a new todolist as @todolist" do
      get :new
      assigns(:todolist).should be_a_new(Todolist)
    end
  end

  describe "GET edit" do
    it "assigns the requested todolist as @todolist" do
      todolist = Todolist.create! valid_attributes
      get :edit, :id => todolist.id.to_s
      assigns(:todolist).should eq(todolist)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Todolist" do
        expect {
          post :create, :todolist => valid_attributes
        }.to change(Todolist, :count).by(1)
      end

      it "assigns a newly created todolist as @todolist" do
        post :create, :todolist => valid_attributes
        assigns(:todolist).should be_a(Todolist)
        assigns(:todolist).should be_persisted
      end

      it "redirects to the created todolist" do
        post :create, :todolist => valid_attributes
        response.should redirect_to(Todolist.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved todolist as @todolist" do
        # Trigger the behavior that occurs when invalid params are submitted
        Todolist.any_instance.stub(:save).and_return(false)
        post :create, :todolist => {}
        assigns(:todolist).should be_a_new(Todolist)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Todolist.any_instance.stub(:save).and_return(false)
        post :create, :todolist => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested todolist" do
        todolist = Todolist.create! valid_attributes
        # Assuming there are no other todolists in the database, this
        # specifies that the Todolist created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Todolist.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => todolist.id, :todolist => {'these' => 'params'}
      end

      it "assigns the requested todolist as @todolist" do
        todolist = Todolist.create! valid_attributes
        put :update, :id => todolist.id, :todolist => valid_attributes
        assigns(:todolist).should eq(todolist)
      end

      it "redirects to the todolist" do
        todolist = Todolist.create! valid_attributes
        put :update, :id => todolist.id, :todolist => valid_attributes
        response.should redirect_to(todolist)
      end
    end

    describe "with invalid params" do
      it "assigns the todolist as @todolist" do
        todolist = Todolist.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Todolist.any_instance.stub(:save).and_return(false)
        put :update, :id => todolist.id.to_s, :todolist => {}
        assigns(:todolist).should eq(todolist)
      end

      it "re-renders the 'edit' template" do
        todolist = Todolist.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Todolist.any_instance.stub(:save).and_return(false)
        put :update, :id => todolist.id.to_s, :todolist => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested todolist" do
      todolist = Todolist.create! valid_attributes
      expect {
        delete :destroy, :id => todolist.id.to_s
      }.to change(Todolist, :count).by(-1)
    end

    it "redirects to the todolists list" do
      todolist = Todolist.create! valid_attributes
      delete :destroy, :id => todolist.id.to_s
      response.should redirect_to(todolists_url)
    end
  end

end
